[env]
EDITOR = 'nvim'

[tools]
# global tool versions go here
# you can set these with `mise use -g`
node = 'latest'
python = ['3.12']
tmux = 'latest'
lua = ['5.1', '5.3', '5.4']
fd = 'latest'
ripgrep = 'latest'
neovim = 'latest'

[plugins]
fd = 'https://gitlab.com/wt0f/asdf-fd'
ripgrep = 'https://gitlab.com/wt0f/asdf-ripgrep'
neovim = 'https://github.com/richin13/asdf-neovim'
tmux = 'https://github.com/aphecetche/asdf-tmux'

[settings]
env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`
experimental = true # enable experimental features

# configure messages displayed when entering directories with config files
status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = true }
