username = "username"
company = "company"
work_email = "work_email"
private_email = "private_email"

[system = "Windows"]
include_path = "C:\Users\${username}\AppData\Roaming\keymapper\include"
scripts_path = "C:\Users\${username}\AppData\Roaming\keymapper\scripts"
keymapperctl_path = "C:\Program Files\keymapper\keymapperctl.exe"
controlMyMonitor_path = "C:\<path\to\ControlMyMonitor\ControlMyMonitor.exe"
